# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendancebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='address',
            name='neighborhood',
        ),
        migrations.AlterUniqueTogether(
            name='neighborhood',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='neighborhood',
            name='city',
        ),
        migrations.RemoveField(
            model_name='yokoshi',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
    ]
