# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-05 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendancebook', '0002_auto_20180112_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='complete_name',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='Yokoshi|complete_name'),
        ),
        migrations.AddField(
            model_name='presence',
            name='first_name',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Yokoshi|first_name'),
        ),
        migrations.AddField(
            model_name='presence',
            name='han',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendancebook.Han', verbose_name='Yokoshi|han'),
        ),
        migrations.AddField(
            model_name='presence',
            name='is_mikumite',
            field=models.BooleanField(default=False, verbose_name='Yokoshi|is_mikumite'),
        ),
        migrations.AddField(
            model_name='presence',
            name='is_mtai',
            field=models.BooleanField(default=False, verbose_name='Yokoshi|is_mtai'),
        ),
        migrations.AddField(
            model_name='presence',
            name='is_ossuewanin',
            field=models.BooleanField(default=False, verbose_name='Yokoshi|is_ossuewanin'),
        ),
        migrations.AddField(
            model_name='presence',
            name='last_name',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Yokoshi|last_name'),
        ),
        migrations.AddField(
            model_name='yokoshi',
            name='first_name',
            field=models.CharField(db_index=True, max_length=300, null=True, verbose_name='Yokoshi|first_name'),
        ),
        migrations.AddField(
            model_name='yokoshi',
            name='last_name',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='Yokoshi|last_name'),
        ),
    ]
