language: python

python:
    - 2.7

install:
    - pip install -r requirements.txt
    - nvm install 0.10
    - npm install

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - suzu/manage.py test
    - npm test