version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    entrypoint: ./run_inside_docker.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db