version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - suzu-network
  web:
    build: .
    entrypoint: ./run_inside_docker.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    networks:
      - suzu-network
    depends_on:
      - db

networks:
  suzu-network:
    driver: bridge