version: '3'

services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5433:5432
  web:
    image: suzusystems/suzu2
    restart: unless-stopped
    entrypoint: ./run_inside_docker.sh
    ports:
      - "8000:8000"
    depends_on:
      - db