version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
  web:
    image: suzusystems/suzu2
    entrypoint: ./run_inside_docker.sh
    ports:
      - "8000:8000"
    depends_on:
      - db